CREATE TABLE IF NOT EXISTS realms (
    realm_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    login_message TEXT,
    login_broadcast TEXT,
    spawn_coord TEXT NOT NULL DEFAULT '0_19_36_38_15',
    respawn_coord TEXT NOT NULL DEFAULT '0_19_36_38_15',
    dev_mode INTEGER NOT NULL DEFAULT 0, -- when 1: LOGIN_OK always ADMIN (gates still use accounts.rights)
    require_registration INTEGER NOT NULL DEFAULT 1,
    auto_assign_display_names INTEGER NOT NULL DEFAULT 0,
    player_xp_rate_in_hundreds INTEGER NOT NULL DEFAULT 100,
    global_xp_rate_in_hundreds INTEGER NOT NULL DEFAULT 100
);
