-- Player-authored `toplevel_v2` layouts.
--
-- Deliberately apart from the layouts the server ships with. Those live in `dbtable.toplevel_v2_preset`
-- in the cache: they are content, the same for everyone, and they change when the cache is rebuilt.
-- These belong to a character, change whenever that character says so, and one character may ask to
-- see another's - none of which is true of the built-in ones, so they do not share a home.
--
-- Six slots per character. One to five are what edit mode offers and are the player's own saves; six
-- is the scratch slot, which the frame keeps in step with whatever is on screen and never lists. A
-- slot with no row has never been written to.
--
-- The scratch slot is what makes leaving without saving safe: the windows come back where they were
-- left, and the named slot the player had loaded is untouched until they say otherwise.
--
-- Which layout a character is currently in is *not* here. That is a varbit on the character, because
-- it is only ever read by the world the character is logged into and never by anyone else - see
-- `varbit.toplevel_v2_layout_slot`.

CREATE TABLE IF NOT EXISTS character_layout_presets (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    character_id INTEGER NOT NULL REFERENCES account_characters (id) ON DELETE CASCADE,
    -- Which of the character's own slots this is. Edit mode's "To: Custom 1".
    slot INTEGER NOT NULL,
    -- Key into `enum.toplevel_v2_layout_name`, or NULL for a layout the player left unnamed. Null
    -- rather than a sentinel: an absent name is an absent value, and the client already treats it
    -- as one.
    name_key INTEGER NULL,
    -- The client window the layout was arranged against, in pixels.
    --
    -- Nothing reads it back to place a window - stored rects are fractions of the client window and
    -- resolve against whatever it is now - but it is what the layout list shows beside a name, so a
    -- player can tell an ultrawide arrangement from a windowed one before loading it. 0 means the
    -- layout predates this being recorded.
    screen_width INTEGER NOT NULL DEFAULT 0,
    screen_height INTEGER NOT NULL DEFAULT 0,
    -- How many times somebody else has loaded this layout.
    --
    -- Only imports by another character count; loading your own back is not an import. Raw hits
    -- rather than distinct importers, which is what makes it cheap - one UPDATE on the way out of
    -- a shared fetch, no second table and no row per event.
    --
    -- Survives the slot being overwritten on purpose: the count belongs to the slot as a thing
    -- people have taken a copy of, and re-arranging what is in it does not undo that.
    import_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_character_layout_presets_slot UNIQUE (character_id, slot),
    CONSTRAINT chk_character_layout_presets_slot CHECK (slot BETWEEN 1 AND 6)
);

-- The leaderboard index.
--
-- Partial on the layouts anyone has ever taken, which is a small fraction of the table, so a top-N
-- read touches only rows that could be in it. `character_id` and `slot` ride along so the query is
-- answered from the index alone - those two are the whole of what a board row needs to identify a
-- layout, and the name and screen size come from a primary-key lookup afterwards.
--
--   SELECT character_id, slot, import_count
--   FROM character_layout_presets
--   WHERE import_count > 0
--   ORDER BY import_count DESC, character_id, slot
--   LIMIT 5;
--
-- The tiebreak is the rest of the index rather than something readable like `updated_at`, so the
-- whole ORDER BY is index order and nothing is sorted. It only decides which of two layouts on the
-- same count comes first, and it has to be *some* fixed answer or the board shuffles between reads.
CREATE INDEX IF NOT EXISTS idx_character_layout_presets_imports
    ON character_layout_presets (import_count DESC, character_id, slot)
    WHERE import_count > 0;

-- Whether a character lets other people load their layouts.
--
-- One answer for the character rather than one per slot. Sharing is a fact about the player - "I
-- don't mind people copying my setup" - not about any particular arrangement of windows, and a
-- per-slot flag would mean answering the same question five times.
--
-- Its own table rather than a column on `account_characters`: it is `toplevel_v2`'s business, and a
-- character who has never touched the frame simply has no row, which reads as not sharing.
CREATE TABLE IF NOT EXISTS character_layout_settings (
    character_id INTEGER PRIMARY KEY REFERENCES account_characters (id) ON DELETE CASCADE,
    -- On by default. Layouts are meant to be passed around - that is most of the point of storing
    -- them centrally rather than on the character - so the setting starts where most people want it
    -- and is there for the ones who do not.
    shared BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Partial index on the ones that have opted *out*, which is the small set.
CREATE INDEX IF NOT EXISTS idx_character_layout_settings_private
    ON character_layout_settings (character_id) WHERE NOT shared;

-- One row per window in the layout.
--
-- `panel` is the panel's row id from `dbtable.toplevel_v2_panel` - what the frame calls a thing,
-- rather than which window slot it happened to be in. Slots are an implementation detail that
-- changes between sessions; the panel does not.
CREATE TABLE IF NOT EXISTS character_layout_windows (
    preset_id INTEGER NOT NULL REFERENCES character_layout_presets (id) ON DELETE CASCADE,
    panel INTEGER NOT NULL,
    x INTEGER NOT NULL,
    y INTEGER NOT NULL,
    width INTEGER NOT NULL,
    height INTEGER NOT NULL,
    -- The panel this one is docked into as a tab, or NULL when it is a window in its own right.
    -- Self-referential by panel rather than by row, so a layout can be copied to another character
    -- without rewriting anything inside it.
    host_panel INTEGER NULL,
    -- Where it sits in its host's tab strip. 0 for an undocked window.
    tab_order INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (preset_id, panel)
);

-- One row per display window - the bank, the central interface, split private chat.
--
-- A separate table from the windows above because they are a separate kind of thing: a window is
-- something the player opens and closes, a display window is somewhere the game puts things whether
-- they asked or not. `display` is the row name's own key from `dbtable.toplevel_v2_display`.
CREATE TABLE IF NOT EXISTS character_layout_displays (
    preset_id INTEGER NOT NULL REFERENCES character_layout_presets (id) ON DELETE CASCADE,
    display INTEGER NOT NULL,
    x INTEGER NOT NULL,
    y INTEGER NOT NULL,
    width INTEGER NOT NULL,
    height INTEGER NOT NULL,
    PRIMARY KEY (preset_id, display)
);
