-- Timestamped counter events, for asking a question over a window of time rather than for all time.
--
-- Deliberately general. `character_gameframe_usage` answers "which display mode is used most" and
-- nothing else, because a tally has thrown the time away by the time you read it - it cannot tell
-- you that a frame doubled the week an update landed, only that it is popular overall. This is where
-- that kind of question is answered, and it is written to be the place any future counter goes
-- rather than one more single-purpose table.
--
-- Only the gameframe writes to it today. Anything else joins by picking a `metric` name and calling
-- the same method; nothing here needs changing for it.
--
-- The two live side by side on purpose. The tally is derivable from these rows and is kept anyway,
-- because the common question - a leaderboard - should not scan a table that grows with every login.
CREATE TABLE IF NOT EXISTS central_metric_events (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    -- What is being counted, as a short name rather than a number.
    --
    -- Text so the table reads on its own and so the game server and the web do not have to keep a
    -- shared enum in step - the cost is a few bytes a row against a column that is almost always
    -- compared for equality against one value.
    metric VARCHAR(32) NOT NULL,
    -- Which one, within that metric. For `gameframe` it is the top-level interface id.
    subject INTEGER NOT NULL,
    -- Who it happened to. Null when a metric is about the world rather than a player.
    character_id INTEGER NULL REFERENCES account_characters (id) ON DELETE SET NULL,
    world_id INTEGER NOT NULL,
    occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- "Everything for this metric between two times", which is the shape of every question asked of it:
--
--   SELECT subject, COUNT(*) AS events
--   FROM central_metric_events
--   WHERE metric = 'gameframe' AND occurred_at >= ? AND occurred_at < ?
--   GROUP BY subject
--   ORDER BY events DESC;
CREATE INDEX IF NOT EXISTS idx_central_metric_events_metric_time
    ON central_metric_events (metric, occurred_at);

-- And the same narrowed to one subject, for plotting a single frame over time. Its own index rather
-- than relying on the one above: filtering by subject after a range scan reads every row in the
-- window, which is exactly the case that gets slow as the table fills.
CREATE INDEX IF NOT EXISTS idx_central_metric_events_subject_time
    ON central_metric_events (metric, subject, occurred_at);

-- Kept forever, on purpose. Nothing prunes this table and nothing should: the whole reason it exists
-- alongside the tally is to answer questions about the past, and a window that only reaches back so
-- far is the one thing that cannot say whether this month is unusual.
--
-- It grows by one row per login, which is small next to what it buys - a year of a busy world is
-- still a table a range scan on either index walks in milliseconds. If it ever does become a
-- problem the answer is rolling old rows up into daily counts per metric and subject, which keeps
-- every question above answerable at coarser resolution; deleting them does not.
