ALTER TABLE exchange_alerts DROP CONSTRAINT IF EXISTS chk_exchange_alerts_kind;
ALTER TABLE exchange_alerts ADD CONSTRAINT chk_exchange_alerts_kind CHECK (
    kind IN (
        'PRICE_CHANGE_24H', 'PRICE_CHANGE_7D', 'VOLUME_CHANGE', 'TRADERS_CHANGE', 'SUSPICIOUS_PATTERN',
        'SINK_FAUCET_IMBALANCE', 'RECONCILIATION', 'SETTLEMENT_LATENCY', 'RETRY_RATE',
        'SYSTEM_NET_GP', 'NEW_ITEM_WATCH', 'COLLECTION_BOX_FULL'
    )
);
